Light.create(property: 'background', value: 'red')
Light.create(property: 'background', value: 'green')
Light.create(property: 'background', value: 'red')
Light.create(property: 'background', value: 'green')
Light.create(property: 'background', value: 'red')
Light.create(property: 'background', value: 'green')
Light.create(property: 'background', value: 'red')
Light.create(property: 'background', value: 'green')
Light.create(property: 'background', value: 'red')
Light.create(property: 'background', value: 'green')

